- name: salt
  electrolyser: true
  booster: false
  ph: true
  redox: true
- name: salt_wo_ph
  electrolyser: true
  booster: false
  ph: false
  redox: true
- name: salt_wo_redox
  electrolyser: true
  booster: false
  ph: true
  redox: false
- name: salt_wo_ph_wo_redox
  electrolyser: true
  booster: false
  ph: false
  redox: false
- name: salt_booster
  electrolyser: true
  booster: true
  ph: true
  redox: true
- name: salt_booster_wo_ph
  electrolyser: true
  booster: true
  ph: false
  redox: true
- name: salt_booster_wo_redox
  electrolyser: true
  booster: true
  ph: true
  redox: false
- name: salt_booster_wo_ph_wo_redox
  electrolyser: true
  booster: true
  ph: false
  redox: false