substitutions:
  name: frangipool
  friendly_name: FrangiPool

wifi:
  ap:
    ssid: $friendly_name Fallback Hostspot
    password: "12345678"
  
esphome:
  name: frangipool
  friendly_name: FrangiPool
  project:
    name: frangipool.redox
    version: "0.1.0"

dashboard_import:
  package_import_url: github://frangipool/esphome-config/frangipool_redox.yaml

esp32:
  board: nodemcu-32s

logger:
  level: INFO

api:

ota:

improv_serial:

esp32_improv:
  authorizer: none

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

ads1115:
  - address: 0x48

globals:
  - id: redox_offset
    type: float
    restore_value: True
  
number:
  - platform: template
    name: Consigne Redox Max
    id: max_redox
    optimistic: True  
    unit_of_measurement: mV
    device_class: voltage
    step: 10
    min_value: 670
    max_value: 750
    restore_value: True
    initial_value: 740
    entity_category: config

  - platform: template
    name: Consigne Redox Min
    id: min_redox
    optimistic: True  
    unit_of_measurement: mV
    device_class: voltage
    step: 10
    min_value: 650
    max_value: 730
    restore_value: True
    initial_value: 710
    entity_category: config

sensor:
  - platform: ads1115
    id: ads1115_a0
    internal: true
    multiplexer: 'A0_GND'
    gain: 6.144
    update_interval: 10s
    filters:
      - median:
          window_size: 12
          send_every: 6

  - platform: template
    name: Redox Temps Réel
    unit_of_measurement: "mV"
    device_class: "voltage"
    state_class: "measurement"
    icon: mdi:chemical-weapon
    id: realtime_redox
    accuracy_decimals: 1
    lambda: return ((2.5-id(ads1115_a0).state)/1.037) + id(redox_offset);
    filters:
      - multiply: 1000
#    on_value_range:
#      - above: !lambda return id(max_redox).state;
#        then:
#        - switch.turn_off: electrolyser
#      - below: !lambda return id(min_redox).state;
#        then:
#        - switch.turn_on: electrolyser    

  - platform: template
    name: Redox Offset
    entity_category: diagnostic
    id: redox_offset_sensor
    lambda: return id(redox_offset);
    
  - platform: uptime
    name: Uptime
    unit_of_measurement: s
    entity_category: diagnostic

  - platform: wifi_signal
    name: RSSI
    update_interval: 60s
    entity_category: diagnostic

binary_sensor:
  - platform: status
    name: Status
    entity_category: diagnostic

switch:
  - platform: gpio
    pin: GPIO27
    name: Electrolyseur
    id: electrolyser
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:chemical-weapon

button: 
  - platform: template
    name: Redox Calibration 225mV
    entity_category: config
    on_press:
      then:
        - globals.set: 
            id: redox_offset
            value: !lambda "return 225 - (((2500-id(ads1115_a0).state)/1.037));"
        - component.update: redox_offset_sensor
        - component.update: realtime_redox

  - platform: template
    name: Redox Calibration 475mV
    entity_category: config
    on_press:
      then:
        - globals.set: 
            id: redox_offset
            value: !lambda "return 475 - (((2500-id(ads1115_a0).state)/1.037));"
        - component.update: redox_offset_sensor
        - component.update: realtime_redox

  - platform: template
    name: Redox Calibration Reset
    entity_category: config
    on_press:
      then:
        - globals.set: 
            id: redox_offset
            value: '0.0'
        - component.update: redox_offset_sensor
        - component.update: realtime_redox

  - platform: restart
    name: Reboot

status_led:
  pin:
    number: GPIO2
    inverted: yes
