substitutions:
  name: frangipool
  friendly_name: FrangiPool
  local_temp_address: '0xC40416C23220FF28'
  temp_address: '0x160121a14aac6f28'

wifi:
  ap:
    ssid: $friendly_name Fallback Hostspot
    password: "12345678"

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: frangipool.salt_booster
    version: "0.1.0"

dashboard_import:
  package_import_url: github://frangipool/esphome-config/frangipool_salt_booster.yaml

esp32:
  board: nodemcu-32s

logger:
  level: INFO

api:

ota:

improv_serial:

esp32_improv:
  authorizer: none

captive_portal:

time:
  - platform: homeassistant
    timezone: Europe/Paris
    id: esptime

dallas:
  - pin: GPIO23
    update_interval: 10s

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

ads1115:
  - address: 0x48

globals:
  - id: pump_last_turn_on
    type: int
    restore_value: True
  - id: store_pool_temp
    type: float
    restore_value: True
  - id: store_pool_redox
    type: float
    restore_value: True
  - id: redox_offset
    type: float
    restore_value: True
  - id: store_pool_ph
    type: float
    restore_value: True
  - id: ph_offset
    type: float
    restore_value: True

interval:
  - interval: 1min
    then:
      - if:
          condition:
            and:
              - switch.is_on: pump
              - lambda: |-
                  if (id(pump_uptime).state >= id(pump_uptime_delay).state){
                    return true;
                  } else {
                    return false;
                  }
          then:
            - globals.set:
                id: store_pool_temp
                value: !lambda "return id(pipe_temp).state;"
            - globals.set:
                id: store_pool_redox
                value: !lambda "return id(realtime_redox).state;"
            - globals.set:
                id: store_pool_ph
                value: !lambda "return id(realtime_ph).state;"

select:
  - platform: template
    name: Mode Filtration
    optimistic: True
    options:
      - Auto
      - On 24h
      - "Off"
      - Hiver
    restore_value: True
    initial_option: Auto
    entity_category: config
    icon: mdi:engine

  - platform: template
    name: Mode Surpresseur
    optimistic: True
    options:
      - "Off"
      - Auto
      - Forcé
    restore_value: True
    initial_option: "Off"
    entity_category: config
    icon: mdi:robot-mower

number:
  - platform: template
    name: Consigne Antigel
    id: max_antifreeze_temp
    optimistic: True
    unit_of_measurement: °C
    device_class: temperature
    step: 0.2
    min_value: -2.0
    max_value: 2.0
    restore_value: True
    initial_value: 0.0
    entity_category: config

  - platform: template
    name: Consigne Redox Max
    id: max_redox
    optimistic: True
    unit_of_measurement: mV
    device_class: voltage
    step: 10
    min_value: 670
    max_value: 750
    restore_value: True
    initial_value: 740
    entity_category: config

  - platform: template
    name: Consigne Redox Min
    id: min_redox
    optimistic: True
    unit_of_measurement: mV
    device_class: voltage
    step: 10
    min_value: 650
    max_value: 730
    restore_value: True
    initial_value: 710
    entity_category: config

  - platform: template
    name: Délais Filtration
    id: pump_uptime_delay
    optimistic: True
    unit_of_measurement: min
    step: 5
    min_value: 5
    max_value: 30
    restore_value: True
    initial_value: 10
    entity_category: config

  # Calibration manuelle, celle-ci sera remise à 0 en cas de calibration Auto
  - platform: template
    entity_category: "diagnostic"
    name: "Redox Calibration Manuelle"
    min_value: -300
    max_value: 300
    step: 1
    optimistic: true
    initial_value: 0
    restore_value: true
    id: "redox_manual_offset"

sensor:
  # Sondes de températures
  - platform: dallas
    address: $local_temp_address
    name: Température Local
    id: local_temp
    accuracy_decimals: 1
    filters:
      - sliding_window_moving_average:
          window_size: 18
          send_every: 6
          send_first_at: 6

  - platform: dallas
    address: $temp_address
    name: Température Canalisation
    accuracy_decimals: 1
    id: pipe_temp
    filters:
      - sliding_window_moving_average:
          window_size: 18
          send_every: 6
          send_first_at: 6
    on_value_range:
      - below: !lambda return id(min_antifreeze_temp).state;
        then:
          - binary_sensor.template.publish:
              id: antifreeze
              state: ON
          - switch.turn_on: pump
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${friendly_name}
              data_template:
                message: Mode hors-gel actif
      - above: !lambda return id(max_antifreeze_temp).state;
        then:
          - binary_sensor.template.publish:
              id: antifreeze
              state: OFF
          - switch.turn_off: pump
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${friendly_name}
              data_template:
                message: Fin du mode hors-gel

  - platform: template
    name: Température Piscine
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    id: pool_temp
    accuracy_decimals: 1
    lambda: |-
      return id(store_pool_temp);

  - platform: template
    name: Pump Uptime
    id: pump_uptime
    internal: True
    lambda: |-
      if (id(pump).state){
        return id(esptime).now().timestamp - id(pump_last_turn_on);
      } else {
        return 0.0;
      }

  - platform: ads1115
    id: ads1115_a0
    internal: true
    multiplexer: 'A0_GND'
    gain: 6.144
    update_interval: 10s
    filters:
      - multiply: 1000

  - platform: template
    name: Redox Temps Réel
    unit_of_measurement: "mV"
    device_class: "voltage"
    state_class: "measurement"
    icon: mdi:chemical-weapon
    entity_category: diagnostic
    id: realtime_redox
    accuracy_decimals: 1
    update_interval: 10s
    lambda: |
      if (id(redox_manual_offset).state != 0.0) return ((2500-id(ads1115_a0).state)/1.037) + id(redox_manual_offset).state;
      else return ((2500-id(ads1115_a0).state)/1.037) + id(redox_offset);
    filters:
      - sliding_window_moving_average:
          window_size: 18
          send_every: 6
          send_first_at: 6

  - platform: template
    name: Redox
    unit_of_measurement: "mV"
    device_class: "voltage"
    state_class: "measurement"
    icon: mdi:chemical-weapon
    id: pool_redox
    accuracy_decimals: 1
    lambda: return id(store_pool_redox);
    on_value_range:
      - above: !lambda return id(max_redox).state;
        then:
        - switch.turn_off: electrolyser
      - below: !lambda return id(min_redox).state;
        then:
        - switch.turn_on: electrolyser

  - platform: template
    name: Redox Offset
    entity_category: diagnostic
    id: redox_offset_sensor
    lambda: return id(redox_offset);

  - platform: ads1115
    id: ads1115_a1
    internal: true
    multiplexer: 'A1_GND'
    gain: 6.144
    update_interval: 10s

  - platform: template
    name: pH Temps Réel
    state_class: "measurement"
    icon: mdi:ph
    entity_category: diagnostic
    id: realtime_ph
    accuracy_decimals: 1
    update_interval: 10s
    lambda: return 3.56 * id(ads1115_a1).state - 1.889 + id(ph_offset);
     filters:
      - sliding_window_moving_average:
          window_size: 18
          send_every: 6
          send_first_at: 6

  - platform: template
    name: pH
    state_class: "measurement"
    icon: mdi:ph
    id: pool_ph
    accuracy_decimals: 1
    lambda: return id(store_pool_ph);

  - platform: template
    name: pH Offset
    entity_category: diagnostic
    id: ph_offset_sensor
    lambda: return id(ph_offset);

  - platform: template
    internal: True
    id: min_antifreeze_temp
    lambda: return id(max_antifreeze_temp).state - 1;

  - platform: uptime
    name: Uptime
    unit_of_measurement: s
    entity_category: diagnostic

  - platform: wifi_signal
    name: RSSI
    update_interval: 60s
    entity_category: diagnostic

binary_sensor:
  - platform: template
    name: Antigel
    device_class: cold
    id: antifreeze
    icon: mdi:snowflake-alert

  - platform: status
    name: Status
    entity_category: diagnostic

switch:
  - platform: gpio
    pin: GPIO25
    name: Filtration
    id: pump
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:engine
    on_turn_on:
      then:
        - globals.set:
            id: pump_last_turn_on
            value: !lambda "return id(esptime).now().timestamp;"

  - platform: gpio
    pin:
      number: GPIO26
      inverted: true
    name: Surpresseur
    id: booster
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:robot-mower

  - platform: gpio
    pin:
      number: GPIO27
      inverted: false
    name: Electrolyseur
    id: electrolyser
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:chemical-weapon

button:
  - platform: template
    name: Redox Calibration 225mV
    entity_category: config
    on_press:
      then:
        - number.set:
            id: redox_manual_offset
            value: 0
        - delay: 180s
        - globals.set:
            id: redox_offset
            value: !lambda "return 225 - (((2500-id(ads1115_a0).state)/1.037));"
        - component.update: redox_offset_sensor
        - component.update: realtime_redox
        - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${friendly_name}
              data_template:
                message: Calibration Redox à 225mV terminée !

  - platform: template
    name: Redox Calibration 475mV
    entity_category: config
    on_press:
      then:
        - number.set:
            id: redox_manual_offset
            value: 0
        - delay: 180s
        - globals.set:
            id: redox_offset
            value: !lambda "return 475 - (((2500-id(ads1115_a0).state)/1.037));"
        - component.update: redox_offset_sensor
        - component.update: realtime_redox
        - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${friendly_name}
              data_template:
                message: Calibration Redox à 475mV terminée !

  - platform: template
    name: Redox Calibration Reset
    entity_category: config
    on_press:
      then:
        - globals.set:
            id: redox_offset
            value: '0.0'
        - component.update: redox_offset_sensor
        - component.update: realtime_redox

  - platform: template
    name: pH Calibration 7.00
    entity_category: config
    on_press:
      then:
        - globals.set:
            id: ph_offset
            value: !lambda "return 7.0 - 3.56 * id(ads1115_a1).state - 1.889;"
        - component.update: ph_offset_sensor
        - component.update: realtime_ph

  - platform: restart
    name: Reboot

status_led:
  pin:
    number: GPIO2
    inverted: yes
