on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - 'template/frangipool.yaml.tmpl'
      - 'template/config.yaml'
name: go-generate
jobs:
  go-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - run: go generate ./...
      - run: git status --ignored
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: '--force'
          commit_message: 'ci(generate): changes by go generate'
          file_pattern: 'frangipool_*.yaml'
          skip_dirty_check: true